"""
Playwright codegen output parser.

This module parses the Python code generated by Playwright codegen and extracts
UI interaction events. It converts Playwright API calls into TraceTap event format.

Key features:
- Parses Python AST to extract page.click(), page.fill(), etc.
- Converts codegen actions to TraceTap events
- Extracts selectors, values, and timestamps
- Supports all major Playwright actions
- HYBRID MODE: Merges codegen actions with trace timestamps for accurate correlation

Reference: Playwright codegen generates async Python code like:
    await page.goto('https://example.com')
    await page.click('#button')
    await page.fill('input[name="email"]', 'user@example.com')
"""

import ast
import re
import logging
import zipfile
import json
from typing import List, Dict, Any, Optional
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)


class CodegenParser:
    """Parser for Playwright codegen output.

    This class parses the Python code generated by Playwright codegen and
    extracts UI interaction events, converting them to TraceTap event format.

    Example:
        parser = CodegenParser()
        events = parser.parse("generated_code.py")

        for event in events:
            print(f"{event['apiName']}: {event['params']}")
    """

    # Map Playwright method names to TraceTap event types
    METHOD_MAP = {
        'goto': 'goto',
        'click': 'click',
        'dblclick': 'dblclick',
        'fill': 'fill',
        'press': 'press',
        'type': 'type',
        'check': 'check',
        'uncheck': 'uncheck',
        'select_option': 'selectOption',
        'hover': 'hover',
        'focus': 'focus',
        'blur': 'blur',
        'set_input_files': 'setInputFiles',
        'drag_and_drop': 'dragAndDrop',
    }

    def __init__(self):
        """Initialize the codegen parser."""
        self.event_sequence = 0
        self.base_timestamp = datetime.now().timestamp() * 1000  # milliseconds

    def parse(self, code_file: str) -> List[Dict[str, Any]]:
        """Parse generated Playwright code into action events.

        Args:
            code_file: Path to the Python file generated by codegen

        Returns:
            List of event dictionaries with TraceTap format

        Raises:
            FileNotFoundError: If code file doesn't exist
            SyntaxError: If code file contains invalid Python syntax
        """
        code_path = Path(code_file)
        if not code_path.exists():
            raise FileNotFoundError(f"Code file not found: {code_file}")

        logger.info(f"📖 Parsing codegen output: {code_file}")

        # Read and parse the Python code
        with open(code_path, 'r', encoding='utf-8') as f:
            code = f.read()

        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            logger.error(f"Failed to parse Python code: {e}")
            raise

        # Extract events from AST
        events = []
        for node in ast.walk(tree):
            event = self._extract_event(node)
            if event:
                events.append(event)
                self.event_sequence += 1

        logger.info(f"✅ Extracted {len(events)} events from codegen output")
        return events

    def _extract_event(self, node: ast.AST) -> Optional[Dict[str, Any]]:
        """Extract event from AST node if it's a relevant Playwright call.

        Args:
            node: AST node to analyze

        Returns:
            Event dictionary if node is a Playwright action, None otherwise
        """
        # Look for await expressions that call page methods
        if isinstance(node, ast.Await):
            call_node = node.value
            if isinstance(call_node, ast.Call):
                return self._parse_call(call_node)

        return None

    def _parse_call(self, call_node: ast.Call) -> Optional[Dict[str, Any]]:
        """Parse a function call node into an event.

        Args:
            call_node: AST Call node

        Returns:
            Event dictionary if call is a supported action, None otherwise
        """
        # Extract method name from page.method() or locator.method()
        method_name = None
        target_object = None

        if isinstance(call_node.func, ast.Attribute):
            method_name = call_node.func.attr

            # Determine the target object (page, locator, etc.)
            if isinstance(call_node.func.value, ast.Name):
                target_object = call_node.func.value.id
            elif isinstance(call_node.func.value, ast.Call):
                # Chained calls like page.locator('.btn').click()
                target_object = 'locator'

        if not method_name or method_name not in self.METHOD_MAP:
            return None

        # Extract arguments
        args = [self._eval_arg(arg) for arg in call_node.args]
        kwargs = {
            kw.arg: self._eval_arg(kw.value)
            for kw in call_node.keywords
        }

        # Build event based on method type
        event = self._build_event(method_name, args, kwargs, target_object)
        return event

    def _build_event(
        self,
        method_name: str,
        args: List[Any],
        kwargs: Dict[str, Any],
        target_object: Optional[str]
    ) -> Dict[str, Any]:
        """Build a TraceTap event from parsed method call.

        Args:
            method_name: Playwright method name
            args: Positional arguments
            kwargs: Keyword arguments
            target_object: Target object name (page, locator, etc.)

        Returns:
            Event dictionary in TraceTap format
        """
        api_name = self.METHOD_MAP[method_name]

        # Base event structure
        event = {
            'type': 'action',
            'apiName': api_name,
            'sequence': self.event_sequence,
            'timestamp': self.base_timestamp + (self.event_sequence * 100),  # 100ms intervals
            'params': {},
        }

        # Method-specific parameter extraction
        if method_name == 'goto':
            event['params']['url'] = args[0] if args else kwargs.get('url', '')

        elif method_name == 'click':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')
            if 'button' in kwargs:
                event['params']['button'] = kwargs['button']
            if 'click_count' in kwargs:
                event['params']['clickCount'] = kwargs['click_count']
            if 'modifiers' in kwargs:
                event['params']['modifiers'] = kwargs['modifiers']

        elif method_name == 'dblclick':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')

        elif method_name == 'fill':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')
            event['params']['value'] = args[1] if len(args) > 1 else kwargs.get('value', '')

        elif method_name == 'press':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')
            event['params']['key'] = args[1] if len(args) > 1 else kwargs.get('key', '')

        elif method_name == 'type':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')
            event['params']['text'] = args[1] if len(args) > 1 else kwargs.get('text', '')
            if 'delay' in kwargs:
                event['params']['delay'] = kwargs['delay']

        elif method_name in ('check', 'uncheck'):
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')

        elif method_name == 'select_option':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')
            # select_option can take value, label, or index
            if len(args) > 1:
                event['params']['values'] = args[1] if isinstance(args[1], list) else [args[1]]
            elif 'value' in kwargs:
                value = kwargs['value']
                event['params']['values'] = value if isinstance(value, list) else [value]
            elif 'label' in kwargs:
                label = kwargs['label']
                event['params']['labels'] = label if isinstance(label, list) else [label]
            elif 'index' in kwargs:
                index = kwargs['index']
                event['params']['indices'] = index if isinstance(index, list) else [index]

        elif method_name == 'hover':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')

        elif method_name in ('focus', 'blur'):
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')

        elif method_name == 'set_input_files':
            event['params']['selector'] = args[0] if args else kwargs.get('selector', '')
            files = args[1] if len(args) > 1 else kwargs.get('files', [])
            event['params']['files'] = files if isinstance(files, list) else [files]

        elif method_name == 'drag_and_drop':
            event['params']['source'] = args[0] if args else kwargs.get('source', '')
            event['params']['target'] = args[1] if len(args) > 1 else kwargs.get('target', '')

        return event

    def _eval_arg(self, arg_node: ast.AST) -> Any:
        """Safely evaluate an argument node to extract its value.

        Args:
            arg_node: AST node representing an argument

        Returns:
            Python value of the argument
        """
        # Handle string literals
        if isinstance(arg_node, ast.Constant):
            return arg_node.value

        # Handle string literals (Python 3.7 compatibility)
        if isinstance(arg_node, ast.Str):
            return arg_node.s

        # Handle number literals
        if isinstance(arg_node, ast.Num):
            return arg_node.n

        # Handle boolean literals
        if isinstance(arg_node, ast.NameConstant):
            return arg_node.value

        # Handle lists
        if isinstance(arg_node, ast.List):
            return [self._eval_arg(elt) for elt in arg_node.elts]

        # Handle dicts
        if isinstance(arg_node, ast.Dict):
            return {
                self._eval_arg(k): self._eval_arg(v)
                for k, v in zip(arg_node.keys, arg_node.values)
            }

        # Handle Name nodes (variables) - return the name as string
        if isinstance(arg_node, ast.Name):
            return f"<var:{arg_node.id}>"

        # Handle attribute access like SomeEnum.VALUE
        if isinstance(arg_node, ast.Attribute):
            return f"{arg_node.attr}"

        # Default: return a representation
        return f"<unparsed:{ast.unparse(arg_node) if hasattr(ast, 'unparse') else '...'}>"

    def parse_with_trace(self, code_file: str, trace_file: str) -> List[Dict[str, Any]]:
        """Parse codegen actions and merge with trace timestamps.

        This is the HYBRID approach: parse codegen for actions (what happened),
        then extract real timestamps from trace.zip (when it happened).

        Args:
            code_file: Path to generated Python code
            trace_file: Path to trace.zip with real timestamps

        Returns:
            List of events with REAL timestamps from trace
        """
        logger.info("🔄 Using HYBRID parsing: codegen actions + trace timestamps")

        # 1. Parse codegen for actions (existing logic)
        actions = self.parse(code_file)
        logger.info(f"   Parsed {len(actions)} actions from codegen")

        # 2. Parse trace.zip for real timestamps
        timestamps = self._extract_timestamps_from_trace(trace_file)
        logger.info(f"   Extracted {len(timestamps)} timestamps from trace")

        # 3. Check if counts match
        if len(actions) != len(timestamps):
            logger.warning(
                f"⚠️  Action count mismatch: {len(actions)} codegen actions vs "
                f"{len(timestamps)} trace timestamps. Using sequential matching."
            )

        # 4. Merge: match actions with timestamps by sequence
        matched_count = min(len(actions), len(timestamps))
        for i in range(matched_count):
            # Replace synthetic timestamp with real timestamp
            actions[i]['timestamp'] = timestamps[i]['timestamp']
            actions[i]['wallTime'] = timestamps[i].get('wallTime')
            actions[i]['startTime'] = timestamps[i].get('startTime')
            actions[i]['endTime'] = timestamps[i].get('endTime')

            # Log the replacement for debugging
            logger.debug(
                f"   Action {i}: {actions[i]['apiName']} "
                f"timestamp={timestamps[i]['timestamp']}"
            )

        # 5. Warn about unmatched actions
        if len(actions) > len(timestamps):
            logger.warning(
                f"⚠️  {len(actions) - len(timestamps)} actions have synthetic timestamps "
                f"(no matching trace events)"
            )

        logger.info(f"✅ Hybrid parsing complete: {matched_count} actions with REAL timestamps")
        return actions

    def _extract_timestamps_from_trace(self, trace_file: str) -> List[Dict[str, Any]]:
        """Extract timestamps from Playwright trace.zip.

        Parses trace.trace (NDJSON) and extracts timestamps from 'before' events
        that represent user interactions.

        Args:
            trace_file: Path to trace.zip

        Returns:
            List of timestamp records in sequence order
        """
        timestamps = []

        try:
            with zipfile.ZipFile(trace_file, 'r') as zip_file:
                # Trace data is in trace.trace file (NDJSON format)
                with zip_file.open('trace.trace') as trace:
                    for line in trace:
                        line = line.strip()
                        if not line:
                            continue

                        try:
                            obj = json.loads(line)

                            # Look for 'before' events that represent actions
                            if obj.get('type') == 'before':
                                method = obj.get('method', '')

                                # Filter for user interaction methods
                                # These match the methods we parse from codegen
                                if method in ['goto', 'click', 'dblclick', 'fill', 'type',
                                            'press', 'check', 'uncheck', 'selectOption',
                                            'hover', 'focus', 'setInputFiles', 'dragAndDrop']:
                                    timestamps.append({
                                        'timestamp': obj.get('wallTime', 0),  # Real wall-clock time
                                        'wallTime': obj.get('wallTime', 0),
                                        'startTime': obj.get('startTime', 0),
                                        'method': method,
                                        'callId': obj.get('callId', '')
                                    })

                        except json.JSONDecodeError:
                            continue

                # Now match 'after' events to get endTime
                # Re-read the file to find 'after' events
                with zip_file.open('trace.trace') as trace:
                    for line in trace:
                        line = line.strip()
                        if not line:
                            continue

                        try:
                            obj = json.loads(line)

                            # Look for 'after' events
                            if obj.get('type') == 'after':
                                call_id = obj.get('callId', '')

                                # Find matching 'before' event by callId
                                for ts in timestamps:
                                    if ts.get('callId') == call_id:
                                        ts['endTime'] = obj.get('endTime', 0)
                                        break

                        except json.JSONDecodeError:
                            continue

        except FileNotFoundError:
            logger.warning(f"⚠️  Trace file not found: {trace_file}")
            return []
        except Exception as e:
            logger.warning(f"⚠️  Failed to extract timestamps from trace: {e}")
            return []

        logger.info(f"📊 Extracted {len(timestamps)} timestamps from trace")
        return timestamps

    def format_events(self, events: List[Dict[str, Any]]) -> str:
        """Format events as pretty-printed JSON.

        Args:
            events: List of event dictionaries

        Returns:
            JSON string representation
        """
        import json
        return json.dumps({'events': events}, indent=2)
