import { test, expect } from '@playwright/test';

// Generated by TraceTap - E-commerce API Regression Tests
// Generated from: checkout-flow.json
// Session: ecommerce-checkout

test.describe('E-commerce API Regression Tests', () => {
  const baseURL = 'http://localhost:5000';

  test.beforeEach(async ({ request }) => {
    // Verify API is healthy before each test
    const health = await request.get(`${baseURL}/health`);
    expect(health.status()).toBe(200);
  });

  test.describe('Product Catalog', () => {
    test('GET /products - List all products', async ({ request }) => {
      const response = await request.get(`${baseURL}/products`);

      expect(response.status()).toBe(200);

      const products = await response.json();
      expect(products).toBeInstanceOf(Array);
      expect(products.length).toBeGreaterThan(0);

      // Validate product structure
      const product = products[0];
      expect(product).toHaveProperty('id');
      expect(product).toHaveProperty('name');
      expect(product).toHaveProperty('price');
      expect(product).toHaveProperty('category');
      expect(product).toHaveProperty('stock');

      // Validate data types
      expect(typeof product.id).toBe('number');
      expect(typeof product.name).toBe('string');
      expect(typeof product.price).toBe('number');
      expect(product.price).toBeGreaterThan(0);
    });

    test('GET /products/{id} - Get product details', async ({ request }) => {
      const productId = 1;
      const response = await request.get(`${baseURL}/products/${productId}`);

      expect(response.status()).toBe(200);

      const product = await response.json();
      expect(product.id).toBe(productId);
      expect(product.name).toBeDefined();
      expect(product.price).toBeGreaterThan(0);
    });

    test('GET /products/{id} - Product not found', async ({ request }) => {
      const response = await request.get(`${baseURL}/products/99999`);

      expect(response.status()).toBe(404);

      const error = await response.json();
      expect(error).toHaveProperty('error');
    });

    test('GET /products?category=Electronics - Filter by category', async ({ request }) => {
      const response = await request.get(`${baseURL}/products?category=Electronics`);

      expect(response.status()).toBe(200);

      const products = await response.json();
      expect(products).toBeInstanceOf(Array);

      // All products should be in Electronics category
      for (const product of products) {
        expect(product.category).toBe('Electronics');
      }
    });
  });

  test.describe('Shopping Cart', () => {
    test('POST /cart - Add item to cart', async ({ request }) => {
      const response = await request.post(`${baseURL}/cart`, {
        data: {
          product_id: 1,
          quantity: 2
        }
      });

      expect(response.status()).toBe(200);

      const result = await response.json();
      expect(result.message).toBe('Item added to cart');
      expect(result.item).toBeDefined();
      expect(result.item.product_id).toBe(1);
      expect(result.item.quantity).toBe(2);
      expect(result.cart_total).toBeGreaterThan(0);
    });

    test('POST /cart - Invalid product', async ({ request }) => {
      const response = await request.post(`${baseURL}/cart`, {
        data: {
          product_id: 99999,
          quantity: 1
        }
      });

      expect(response.status()).toBe(404);

      const error = await response.json();
      expect(error.error).toContain('not found');
    });

    test('POST /cart - Missing product_id', async ({ request }) => {
      const response = await request.post(`${baseURL}/cart`, {
        data: {
          quantity: 1
        }
      });

      expect(response.status()).toBe(400);

      const error = await response.json();
      expect(error.error).toContain('product_id');
    });

    test('GET /cart - View cart contents', async ({ request }) => {
      // First add an item
      await request.post(`${baseURL}/cart`, {
        data: { product_id: 2, quantity: 1 }
      });

      const response = await request.get(`${baseURL}/cart`);

      expect(response.status()).toBe(200);

      const cart = await response.json();
      expect(cart).toHaveProperty('items');
      expect(cart).toHaveProperty('total');
      expect(cart).toHaveProperty('item_count');
      expect(cart.items).toBeInstanceOf(Array);
    });
  });

  test.describe('Checkout Flow', () => {
    test('Complete checkout flow', async ({ request }) => {
      // Step 1: Browse products
      const productsResponse = await request.get(`${baseURL}/products`);
      expect(productsResponse.status()).toBe(200);
      const products = await productsResponse.json();
      expect(products.length).toBeGreaterThan(0);

      // Step 2: View product details
      const productId = products[0].id;
      const productResponse = await request.get(`${baseURL}/products/${productId}`);
      expect(productResponse.status()).toBe(200);
      const product = await productResponse.json();

      // Step 3: Add to cart
      const addToCartResponse = await request.post(`${baseURL}/cart`, {
        data: {
          product_id: productId,
          quantity: 2
        }
      });
      expect(addToCartResponse.status()).toBe(200);

      // Step 4: Add another item
      const addAnotherResponse = await request.post(`${baseURL}/cart`, {
        data: {
          product_id: 3,
          quantity: 1
        }
      });
      expect(addAnotherResponse.status()).toBe(200);

      // Step 5: View cart
      const cartResponse = await request.get(`${baseURL}/cart`);
      expect(cartResponse.status()).toBe(200);
      const cart = await cartResponse.json();
      expect(cart.item_count).toBe(2);
      expect(cart.total).toBeGreaterThan(0);

      // Step 6: Checkout
      const checkoutResponse = await request.post(`${baseURL}/checkout`, {
        data: {
          payment_method: 'credit_card',
          shipping_address: '123 Main St, Anytown, ST 12345'
        }
      });
      expect(checkoutResponse.status()).toBe(201);

      const order = await checkoutResponse.json();
      expect(order.id).toBeDefined();
      expect(order.status).toBe('confirmed');
      expect(order.total).toBe(cart.total);
      expect(order.items.length).toBe(cart.item_count);
      expect(order.estimated_delivery).toBeDefined();

      // Step 7: Check order status
      const orderResponse = await request.get(`${baseURL}/orders/${order.id}`);
      expect(orderResponse.status()).toBe(200);

      const orderStatus = await orderResponse.json();
      expect(orderStatus.id).toBe(order.id);
      expect(orderStatus.status).toBe('confirmed');
    });

    test('POST /checkout - Empty cart', async ({ request }) => {
      // Ensure cart is empty first
      const cartResponse = await request.get(`${baseURL}/cart`);
      const cart = await cartResponse.json();

      // Only test if cart is actually empty
      if (cart.items.length === 0) {
        const response = await request.post(`${baseURL}/checkout`, {
          data: {
            payment_method: 'credit_card',
            shipping_address: '123 Main St'
          }
        });

        expect(response.status()).toBe(400);

        const error = await response.json();
        expect(error.error).toContain('empty');
      }
    });

    test('POST /checkout - Missing shipping address', async ({ request }) => {
      // Add item first
      await request.post(`${baseURL}/cart`, {
        data: { product_id: 1, quantity: 1 }
      });

      const response = await request.post(`${baseURL}/checkout`, {
        data: {
          payment_method: 'credit_card'
        }
      });

      expect(response.status()).toBe(400);

      const error = await response.json();
      expect(error.error).toContain('shipping_address');
    });
  });

  test.describe('Order Management', () => {
    test('GET /orders/{id} - Get order status', async ({ request }) => {
      // Create an order first
      await request.post(`${baseURL}/cart`, {
        data: { product_id: 2, quantity: 1 }
      });

      const checkoutResponse = await request.post(`${baseURL}/checkout`, {
        data: {
          payment_method: 'credit_card',
          shipping_address: '456 Oak Ave'
        }
      });

      const order = await checkoutResponse.json();

      // Get order status
      const response = await request.get(`${baseURL}/orders/${order.id}`);

      expect(response.status()).toBe(200);

      const orderStatus = await response.json();
      expect(orderStatus.id).toBe(order.id);
      expect(orderStatus.status).toBe('confirmed');
      expect(orderStatus.items).toBeDefined();
      expect(orderStatus.total).toBeDefined();
    });

    test('GET /orders/{id} - Order not found', async ({ request }) => {
      const response = await request.get(`${baseURL}/orders/99999`);

      expect(response.status()).toBe(404);

      const error = await response.json();
      expect(error.error).toContain('not found');
    });
  });
});
