/**
 * Playwright API Tests
 * Generated from Postman Collection: My API Collection
 * Generated on: 2025-12-09 13:45:47
 *
 * This file was automatically generated by TraceTap.
 * You may need to adjust authentication and environment variables.
 */

import { test as base, expect } from '@playwright/test';
type CustomFixtures = {
  baseUrl: string;
};

const test = base.extend<CustomFixtures>({
  baseUrl: async ({}, use) => {
  // Use environment variable if available, otherwise use collection default
  const url = process.env.BASE_URL || 'https://api.example.com';
  await use(url);
}
});

test.describe('My API Collection', () => {
  // Authenticates user and returns JWT token.

Custom note: This endpoint is critical for auth flow.
  test('Login User', async ({ request, baseUrl, username, password }) => {
    const response = await request.post(`${baseUrl}/auth/login`, { headers: { 'Content-Type': 'application/json' }, data: { 'username': `${username}`, 'password': `${password}` } });

    // Status is 200
    expect(response.status()).toBe(200);
    // Status is 200
    const response = await response.json();
    // Store authToken
    const authToken = response.token;

    // Extract variables for use in later tests
    // Extract auth_token from response
    const authToken = response.token;
  });

  // Fetches current user profile.

My custom documentation here.
  test('Get User Profile', async ({ request, baseUrl, authToken }) => {
    const response = await request.get(`${baseUrl}/users/123`, { headers: { 'Authorization': `Bearer ${authToken}`, 'X-Custom-Header': 'my-custom-value' } });

    // User has email
    const user = await response.json();
    // User has email
    expect(user.email).toBeTruthy();

  });

  test('Update User', async ({ request, baseUrl, authToken, newName, newEmail }) => {
    const response = await request.put(`${baseUrl}/users/123`, { headers: { 'Authorization': `Bearer ${authToken}` }, data: { 'name': `${newName}`, 'email': `${newEmail}` } });

  });

  test('Delete Old Endpoint', async ({ request, baseUrl }) => {
    const response = await request.delete(`${baseUrl}/legacy/old-endpoint`);

  });

});
