import { test, expect } from '@playwright/test';

// Generated by TraceTap - REST API Regression Suite
// Generated from: crud-operations.json
// Assertion levels: status, schema, data

test.describe('REST API Regression Tests', () => {
  const baseURL = process.env.API_URL || 'http://localhost:3000';

  test.describe('User CRUD Operations', () => {

    test.describe('CREATE - POST /users', () => {
      test('should create a new user with valid data', async ({ request }) => {
        const response = await request.post(`${baseURL}/users`, {
          data: {
            name: 'Test User',
            email: `test-${Date.now()}@example.com`,
            role: 'user'
          }
        });

        // Status assertion
        expect(response.status()).toBe(201);

        // Schema assertions
        const user = await response.json();
        expect(user).toHaveProperty('id');
        expect(user).toHaveProperty('name');
        expect(user).toHaveProperty('email');
        expect(user).toHaveProperty('role');
        expect(user).toHaveProperty('status');
        expect(user).toHaveProperty('created_at');

        // Data type assertions
        expect(typeof user.id).toBe('number');
        expect(typeof user.name).toBe('string');
        expect(typeof user.email).toBe('string');

        // Value assertions
        expect(user.status).toBe('active');
        expect(user.email).toMatch(/@example\.com$/);

        // Location header
        expect(response.headers()['location']).toBe(`/users/${user.id}`);
      });

      test('should return 400 for missing required fields', async ({ request }) => {
        const response = await request.post(`${baseURL}/users`, {
          data: {
            name: 'Invalid User'
            // Missing email
          }
        });

        expect(response.status()).toBe(400);

        const error = await response.json();
        expect(error).toHaveProperty('error');
        expect(error).toHaveProperty('details');
        expect(error.details).toHaveProperty('email');
      });

      test('should return 409 for duplicate email', async ({ request }) => {
        const email = `duplicate-${Date.now()}@example.com`;

        // Create first user
        await request.post(`${baseURL}/users`, {
          data: { name: 'First', email, role: 'user' }
        });

        // Attempt to create duplicate
        const response = await request.post(`${baseURL}/users`, {
          data: { name: 'Second', email, role: 'user' }
        });

        expect(response.status()).toBe(409);

        const error = await response.json();
        expect(error.error).toContain('already exists');
      });
    });

    test.describe('READ - GET /users', () => {
      test('should list all users', async ({ request }) => {
        const response = await request.get(`${baseURL}/users`);

        expect(response.status()).toBe(200);

        const users = await response.json();
        expect(users).toBeInstanceOf(Array);

        // Validate total count header
        const totalCount = response.headers()['x-total-count'];
        expect(parseInt(totalCount)).toBe(users.length);

        // If users exist, validate structure
        if (users.length > 0) {
          const user = users[0];
          expect(user).toHaveProperty('id');
          expect(user).toHaveProperty('name');
          expect(user).toHaveProperty('email');
          expect(user).toHaveProperty('role');
          expect(user).toHaveProperty('status');
        }
      });

      test('should filter users by role', async ({ request }) => {
        const response = await request.get(`${baseURL}/users?role=admin`);

        expect(response.status()).toBe(200);

        const users = await response.json();
        expect(users).toBeInstanceOf(Array);

        // All returned users should have admin role
        for (const user of users) {
          expect(user.role).toBe('admin');
        }
      });
    });

    test.describe('READ - GET /users/{id}', () => {
      test('should get user by ID', async ({ request }) => {
        // First create a user
        const createResponse = await request.post(`${baseURL}/users`, {
          data: {
            name: 'Get Test',
            email: `get-test-${Date.now()}@example.com`,
            role: 'user'
          }
        });
        const createdUser = await createResponse.json();

        // Then get by ID
        const response = await request.get(`${baseURL}/users/${createdUser.id}`);

        expect(response.status()).toBe(200);

        const user = await response.json();
        expect(user.id).toBe(createdUser.id);
        expect(user.name).toBe('Get Test');
        expect(user.email).toBe(createdUser.email);
      });

      test('should return 404 for non-existent user', async ({ request }) => {
        const response = await request.get(`${baseURL}/users/99999`);

        expect(response.status()).toBe(404);

        const error = await response.json();
        expect(error).toHaveProperty('error');
        expect(error.error).toContain('not found');
      });
    });

    test.describe('UPDATE - PUT /users/{id}', () => {
      test('should fully update user', async ({ request }) => {
        // Create user
        const createResponse = await request.post(`${baseURL}/users`, {
          data: {
            name: 'Original Name',
            email: `update-test-${Date.now()}@example.com`,
            role: 'user'
          }
        });
        const createdUser = await createResponse.json();

        // Update user
        const response = await request.put(`${baseURL}/users/${createdUser.id}`, {
          data: {
            name: 'Updated Name',
            email: `updated-${Date.now()}@example.com`
          }
        });

        expect(response.status()).toBe(200);

        const user = await response.json();
        expect(user.id).toBe(createdUser.id);
        expect(user.name).toBe('Updated Name');
        expect(user).toHaveProperty('updated_at');
      });
    });

    test.describe('UPDATE - PATCH /users/{id}', () => {
      test('should partially update user', async ({ request }) => {
        // Create user
        const createResponse = await request.post(`${baseURL}/users`, {
          data: {
            name: 'Patch Test',
            email: `patch-test-${Date.now()}@example.com`,
            role: 'user'
          }
        });
        const createdUser = await createResponse.json();

        // Patch user
        const response = await request.patch(`${baseURL}/users/${createdUser.id}`, {
          data: {
            status: 'inactive'
          }
        });

        expect(response.status()).toBe(200);

        const user = await response.json();
        expect(user.id).toBe(createdUser.id);
        expect(user.name).toBe('Patch Test'); // Unchanged
        expect(user.status).toBe('inactive'); // Changed
        expect(user).toHaveProperty('updated_at');
      });
    });

    test.describe('DELETE - DELETE /users/{id}', () => {
      test('should delete user', async ({ request }) => {
        // Create user
        const createResponse = await request.post(`${baseURL}/users`, {
          data: {
            name: 'Delete Test',
            email: `delete-test-${Date.now()}@example.com`,
            role: 'user'
          }
        });
        const createdUser = await createResponse.json();

        // Delete user
        const response = await request.delete(`${baseURL}/users/${createdUser.id}`);

        expect(response.status()).toBe(204);

        // Verify deleted
        const getResponse = await request.get(`${baseURL}/users/${createdUser.id}`);
        expect(getResponse.status()).toBe(404);
      });

      test('should return 404 for non-existent user', async ({ request }) => {
        const response = await request.delete(`${baseURL}/users/99999`);

        // Could be 404 or 204 depending on API design
        expect([204, 404]).toContain(response.status());
      });
    });
  });

  test.describe('Complete CRUD Workflow', () => {
    test('should perform complete CRUD lifecycle', async ({ request }) => {
      const uniqueEmail = `workflow-${Date.now()}@example.com`;

      // CREATE
      const createResponse = await request.post(`${baseURL}/users`, {
        data: {
          name: 'Workflow User',
          email: uniqueEmail,
          role: 'user'
        }
      });
      expect(createResponse.status()).toBe(201);
      const created = await createResponse.json();
      const userId = created.id;

      // READ - List
      const listResponse = await request.get(`${baseURL}/users`);
      expect(listResponse.status()).toBe(200);
      const users = await listResponse.json();
      const foundUser = users.find((u: any) => u.id === userId);
      expect(foundUser).toBeDefined();

      // READ - Single
      const getResponse = await request.get(`${baseURL}/users/${userId}`);
      expect(getResponse.status()).toBe(200);
      const fetched = await getResponse.json();
      expect(fetched.id).toBe(userId);

      // UPDATE
      const updateResponse = await request.put(`${baseURL}/users/${userId}`, {
        data: {
          name: 'Updated Workflow User',
          email: uniqueEmail
        }
      });
      expect(updateResponse.status()).toBe(200);
      const updated = await updateResponse.json();
      expect(updated.name).toBe('Updated Workflow User');

      // DELETE
      const deleteResponse = await request.delete(`${baseURL}/users/${userId}`);
      expect(deleteResponse.status()).toBe(204);

      // VERIFY DELETED
      const verifyResponse = await request.get(`${baseURL}/users/${userId}`);
      expect(verifyResponse.status()).toBe(404);
    });
  });

  test.describe('Error Handling', () => {
    test('should handle invalid JSON gracefully', async ({ request }) => {
      const response = await request.post(`${baseURL}/users`, {
        headers: { 'Content-Type': 'application/json' },
        data: 'invalid json' as any
      });

      expect([400, 415, 422]).toContain(response.status());
    });

    test('should handle missing content-type', async ({ request }) => {
      const response = await request.post(`${baseURL}/users`, {
        data: { name: 'Test' }
      });

      // Should either accept or reject gracefully
      expect([201, 400, 415]).toContain(response.status());
    });
  });
});
